### ISSUE TITLE
Development Checklist

### ISSUE THREAD

**Issue by edumaciel10** [edumaciel10/games-catalog-c#4]
- [x] Deixar a lista circular
- [x] Mover ITEM para JOGO
- [x] Criar nova pasta e sair da implementação do Leo
- [x] Talvez LISTA para CATALOGO
- [x] Começar a criar o main corretamente
- [x] Suportar os inputs pelo csv
- [x] Função p ( retornar todos os jogos da produtora)
- [x] Função a ( retornar todos os jogos por ano) 
- [x] Função I  ( imprimir o nome de todos os jogos seguindo o 
- [x] Função u (imprimir o nome do jogo da posição especificada)
- [x] Funções mr e ml  (mover nodes dentro da lista)
